spring:
  main:
    allow-circular-references: true
    web-application-type: reactive
  application:
    name: review-service
  jpa:
    hibernate:
      ddl-auto: create # none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100 # 배치전략을 위해 필요
    #database: mysql
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://220.125.53.144:8761/eureka

logging.level:
  org.hibernate.SQL: debug

server:
  port: 8081