spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r!
    url: jdbc:mysql://localhost:3306/suggestion_service_db?characterEncoding=UTF-8
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
  messages:
    basename: messages, errors