eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: 'true'
  client:
    register-with-eureka: 'true'
    service-url:
      defaultZone: http://220.125.53.144:8761/eureka
    fetch-registry: 'true'
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: mysql
    username: root
    url: jdbc:mysql://localhost:3306/userserviceDB?characterEncoding=UTF-8
  application:
    name: user-service
  h2:
    console:
      path: /h2-console
      enabled: 'true'
      settings:
        web-allow-others: 'true'
  jpa:
    hibernate:
      ddl-auto: create
security:
  jwt:
    token:
      secret-key: amFuZ2phbmdqYW5namFuZ2phbmdqYW5namFuZ2phbmc=
      expire-time: '300000'
server:
  port: '0'
